// Map of exercise names to their primary muscle group
// Resistance-training focused, gym-centric.
// Primary target only; many movements have strong secondary muscles.
const exerciseMuscleMap = {
  // ===== Chest =====
  'Bench Press': 'chest',
  'Barbell Bench Press': 'chest',
  'Dumbbell Bench Press': 'chest',
  'Machine Chest Press': 'chest',
  'Smith Machine Bench Press': 'chest',
  'Incline Bench Press': 'chest',
  'Incline Barbell Press': 'chest',
  'Incline Dumbbell Press': 'chest',
  'Incline Machine Press': 'chest',
  'Decline Bench Press': 'chest',
  'Decline Dumbbell Press': 'chest',
  'Decline Machine Press': 'chest',
  'Push Up': 'chest',
  'Weighted Push Up': 'chest',
  'Cable Fly': 'chest',
  'High-to-Low Cable Fly': 'chest',
  'Low-to-High Cable Fly': 'chest',
  'Pec Deck': 'chest',
  'Chest Fly': 'chest',
  'Dumbbell Fly': 'chest',
  'Chest Dip': 'chest',
  'Svend Press': 'chest',
  'Landmine Press (Chest Focus)': 'chest',

  // ===== Back (lats + general back) =====
  'Deadlift': 'back',
  'Conventional Deadlift': 'back',
  'Trap Bar Deadlift': 'back',
  'Sumo Deadlift': 'back',
  'Barbell Row': 'back',
  'Bent-Over Barbell Row': 'back',
  'Pendlay Row': 'back',
  'T-Bar Row': 'back',
  'Chest Supported Row': 'back',
  'Seal Row': 'back',
  'Dumbbell Row': 'back',
  'Single-Arm Dumbbell Row': 'back',
  'Meadows Row': 'back',
  'Inverted Row': 'back',
  'Cable Row': 'back',
  'Seated Cable Row': 'back',
  'Machine Row': 'back',
  'Hammer Strength Row': 'back',
  'Lat Pulldown': 'back',
  'Wide-Grip Lat Pulldown': 'back',
  'Close-Grip Lat Pulldown': 'back',
  'Neutral-Grip Lat Pulldown': 'back',
  'Straight-Arm Pulldown': 'back',
  'Pull Up': 'back',
  'Chin Up': 'back',
  'Neutral-Grip Pull Up': 'back',
  'Assisted Pull Up': 'back',
  'Pullover (Machine)': 'back',
  'Dumbbell Pullover': 'back',
  'Cable Pullover': 'back',
  'Landmine Row': 'back',
  'Kroc Row': 'back',

  // ===== Shoulders =====
  'Overhead Press': 'shoulders',
  'Barbell Overhead Press': 'shoulders',
  'Standing Overhead Press': 'shoulders',
  'Seated Overhead Press': 'shoulders',
  'Dumbbell Shoulder Press': 'shoulders',
  'Seated Dumbbell Press': 'shoulders',
  'Arnold Press': 'shoulders',
  'Machine Shoulder Press': 'shoulders',
  'Smith Machine Overhead Press': 'shoulders',
  'Lateral Raise': 'shoulders',
  'Cable Lateral Raise': 'shoulders',
  'Machine Lateral Raise': 'shoulders',
  'Dumbbell Lateral Raise': 'shoulders',
  'Front Raise': 'shoulders',
  'Plate Front Raise': 'shoulders',
  'Cable Front Raise': 'shoulders',
  'Rear Delt Fly': 'shoulders',
  'Reverse Pec Deck': 'shoulders',
  'Cable Rear Delt Fly': 'shoulders',
  'Face Pull': 'shoulders',
  'Upright Row': 'shoulders',
  'Landmine Press': 'shoulders',

  // ===== Traps =====
  'Barbell Shrug': 'traps',
  'Dumbbell Shrug': 'traps',
  'Smith Machine Shrug': 'traps',
  'Cable Shrug': 'traps',
  'Behind-the-Back Barbell Shrug': 'traps',
  "Farmer's Walk": 'traps',

  // ===== Biceps =====
  'Curl': 'biceps',
  'Barbell Curl': 'biceps',
  'EZ-Bar Curl': 'biceps',
  'Dumbbell Curl': 'biceps',
  'Alternating Dumbbell Curl': 'biceps',
  'Incline Dumbbell Curl': 'biceps',
  'Seated Dumbbell Curl': 'biceps',
  'Preacher Curl': 'biceps',
  'Machine Preacher Curl': 'biceps',
  'Cable Curl': 'biceps',
  'Rope Cable Curl': 'biceps',
  'Concentration Curl': 'biceps',
  'Spider Curl': 'biceps',
  'Bayesian Cable Curl': 'biceps',
  'Hammer Curl': 'biceps',
  'Cross-Body Hammer Curl': 'biceps',
  'Reverse Curl': 'biceps',
  'Zottman Curl': 'biceps',

  // ===== Triceps =====
  'Dip': 'triceps',
  'Triceps Dip': 'triceps',
  'Close-Grip Bench Press': 'triceps',
  'Skull Crusher': 'triceps',
  'EZ-Bar Skull Crusher': 'triceps',
  'Lying Triceps Extension': 'triceps',
  'Overhead Triceps Extension': 'triceps',
  'Seated Overhead Dumbbell Extension': 'triceps',
  'Cable Overhead Triceps Extension': 'triceps',
  'Triceps Pushdown': 'triceps',
  'Cable Triceps Pushdown': 'triceps',
  'Rope Pushdown': 'triceps',
  'V-Bar Pushdown': 'triceps',
  'Single-Arm Cable Pushdown': 'triceps',
  'Kickback': 'triceps',
  'Dumbbell Triceps Kickback': 'triceps',
  'Machine Triceps Extension': 'triceps',

  // ===== Forearms =====
  'Wrist Curl': 'forearms',
  'Reverse Wrist Curl': 'forearms',
  'Behind-the-Back Wrist Curl': 'forearms',
  'Wrist Roller': 'forearms',
  'Plate Pinch': 'forearms',
  'Reverse Curl (Forearm Focus)': 'forearms',
  "Farmer's Carry": 'forearms',
  'Towel Pull Up': 'forearms',

  // ===== Quads =====
  'Squat': 'quads',
  'Back Squat': 'quads',
  'High-Bar Squat': 'quads',
  'Front Squat': 'quads',
  'Smith Machine Squat': 'quads',
  'Hack Squat': 'quads',
  'Machine Hack Squat': 'quads',
  'Sissy Squat': 'quads',
  'Goblet Squat': 'quads',
  'Leg Extension': 'quads',
  'Single-Leg Extension': 'quads',
  'Leg Press': 'quads',
  'Narrow-Stance Leg Press': 'quads',
  'Walking Lunge': 'quads',
  'Forward Lunge': 'quads',
  'Reverse Lunge': 'quads',
  'Deficit Lunge': 'quads',
  'Split Squat': 'quads',
  'Bulgarian Split Squat': 'quads',
  'Step Up': 'quads',

  // ===== Hamstrings =====
  'Romanian Deadlift': 'hamstrings',
  'Stiff-Leg Deadlift': 'hamstrings',
  'Good Morning': 'hamstrings',
  'Leg Curl': 'hamstrings',
  'Seated Leg Curl': 'hamstrings',
  'Lying Leg Curl': 'hamstrings',
  'Standing Leg Curl': 'hamstrings',
  'Nordic Curl': 'hamstrings',
  'Glute-Ham Raise': 'hamstrings',
  'Cable Pull-Through (Hamstrings)': 'hamstrings',
  'Back Extension (Hamstrings)': 'hamstrings',

  // ===== Glutes =====
  'Hip Thrust': 'glutes',
  'Barbell Hip Thrust': 'glutes',
  'Smith Machine Hip Thrust': 'glutes',
  'Glute Bridge': 'glutes',
  'Single-Leg Hip Thrust': 'glutes',
  'Cable Pull-Through': 'glutes',
  'Kettlebell Swing': 'glutes',
  'Step-Up (Glute Focus)': 'glutes',
  'Reverse Lunge (Glute Focus)': 'glutes',
  'Curtsy Lunge': 'glutes',
  '45-Degree Back Extension (Glutes)': 'glutes',
  'Frog Pump': 'glutes',
  'Hip Abduction (Cable)': 'glutes',

  // ===== Calves =====
  'Calf Raise': 'calves',
  'Standing Calf Raise': 'calves',
  'Seated Calf Raise': 'calves',
  'Donkey Calf Raise': 'calves',
  'Leg Press Calf Raise': 'calves',
  'Single-Leg Calf Raise': 'calves',
  'Smith Machine Calf Raise': 'calves',
  'Tibialis Raise': 'calves', // anterior lower leg; keep under calves for simplicity

  // ===== Adductors / Abductors =====
  'Hip Adductor Machine': 'adductors',
  'Hip Abductor Machine': 'abductors',
  'Cable Hip Adduction': 'adductors',
  'Cable Hip Abduction': 'abductors',
  'Side-Lying Hip Abduction': 'abductors',

  // ===== Core / Abs =====
  'Crunch': 'abs',
  'Cable Crunch': 'abs',
  'Machine Crunch': 'abs',
  'Decline Crunch': 'abs',
  'Hanging Knee Raise': 'abs',
  'Hanging Leg Raise': 'abs',
  "Captain's Chair Leg Raise": 'abs',
  'Reverse Crunch': 'abs',
  'Ab Wheel Rollout': 'abs',
  'Plank (Weighted)': 'abs',
  'Side Plank (Weighted)': 'abs',
  'Russian Twist (Weighted)': 'abs',
  'Pallof Press': 'abs',
  'Toe Touch (Weighted)': 'abs',

  // ===== Lower Back (grouped under back for simplicity) =====
  'Back Extension': 'back',
  '45-Degree Back Extension': 'back',
  'Reverse Hyperextension': 'back',
  'Superman (Weighted)': 'back',

  // ===== Misc / Full-body (choose primary) =====
  'Clean Pull': 'back',
  'Snatch Pull': 'back',
  'Power Clean (Strength Accessory)': 'back',
  'Landmine Deadlift': 'back',
  'Sled Push': 'legs',
  'Sled Drag': 'hamstrings',
  "Farmer's Walk (Heavy)": 'traps',
  'Yoke Carry': 'traps',
};

// === AUTO-GENERATED: BEGIN (scripts/sync-exercise-muscle-map.js) ===
// Generated from data/free-exercise-db.min.json — DO NOT EDIT BY HAND.
// Re-run `node scripts/sync-exercise-muscle-map.js` to refresh.
// Hand-curated names above always take priority over this block.
const generatedExerciseMuscleMap = {
  "3/4 Sit-Up": "abs",
  "90/90 Hamstring": "hamstrings",
  "Ab Crunch Machine": "abs",
  "Ab Roller": "abs",
  "Adductor": "adductors",
  "Adductor/Groin": "adductors",
  "Advanced Kettlebell Windmill": "abs",
  "Air Bike": "abs",
  "All Fours Quad Stretch": "quads",
  "Alternate Hammer Curl": "biceps",
  "Alternate Heel Touchers": "abs",
  "Alternate Incline Dumbbell Curl": "biceps",
  "Alternate Leg Diagonal Bound": "quads",
  "Alternating Cable Shoulder Press": "shoulders",
  "Alternating Deltoid Raise": "shoulders",
  "Alternating Floor Press": "chest",
  "Alternating Hang Clean": "hamstrings",
  "Alternating Kettlebell Press": "shoulders",
  "Alternating Kettlebell Row": "back",
  "Alternating Renegade Row": "back",
  "Ankle Circles": "calves",
  "Ankle On The Knee": "glutes",
  "Anterior Tibialis-SMR": "calves",
  "Anti-Gravity Press": "shoulders",
  "Arm Circles": "shoulders",
  "Arnold Dumbbell Press": "shoulders",
  "Around The Worlds": "chest",
  "Atlas Stone Trainer": "back",
  "Atlas Stones": "back",
  "Axle Deadlift": "back",
  "Back Flyes - With Bands": "shoulders",
  "Backward Drag": "quads",
  "Backward Medicine Ball Throw": "shoulders",
  "Balance Board": "calves",
  "Ball Leg Curl": "hamstrings",
  "Band Assisted Pull-Up": "back",
  "Band Good Morning": "hamstrings",
  "Band Good Morning (Pull Through)": "hamstrings",
  "Band Hip Adductions": "adductors",
  "Band Pull Apart": "shoulders",
  "Band Skull Crusher": "triceps",
  "Barbell Ab Rollout": "abs",
  "Barbell Ab Rollout - On Knees": "abs",
  "Barbell Bench Press - Medium Grip": "chest",
  "Barbell Curls Lying Against An Incline": "biceps",
  "Barbell Deadlift": "back",
  "Barbell Full Squat": "quads",
  "Barbell Glute Bridge": "glutes",
  "Barbell Guillotine Bench Press": "chest",
  "Barbell Hack Squat": "quads",
  "Barbell Incline Bench Press - Medium Grip": "chest",
  "Barbell Incline Shoulder Raise": "shoulders",
  "Barbell Lunge": "quads",
  "Barbell Rear Delt Row": "shoulders",
  "Barbell Rollout from Bench": "abs",
  "Barbell Seated Calf Raise": "calves",
  "Barbell Shoulder Press": "shoulders",
  "Barbell Shrug Behind The Back": "traps",
  "Barbell Side Bend": "abs",
  "Barbell Side Split Squat": "quads",
  "Barbell Squat": "quads",
  "Barbell Squat To A Bench": "quads",
  "Barbell Step Ups": "quads",
  "Barbell Walking Lunge": "quads",
  "Battling Ropes": "shoulders",
  "Bear Crawl Sled Drags": "quads",
  "Behind Head Chest Stretch": "chest",
  "Bench Dips": "triceps",
  "Bench Jump": "quads",
  "Bench Press - Powerlifting": "triceps",
  "Bench Press - With Bands": "chest",
  "Bench Press with Chains": "triceps",
  "Bench Sprint": "quads",
  "Bent Over Barbell Row": "back",
  "Bent Over Dumbbell Rear Delt Raise With Head On Bench": "shoulders",
  "Bent Over Low-Pulley Side Lateral": "shoulders",
  "Bent Over One-Arm Long Bar Row": "back",
  "Bent Over Two-Arm Long Bar Row": "back",
  "Bent Over Two-Dumbbell Row": "back",
  "Bent Over Two-Dumbbell Row With Palms In": "back",
  "Bent Press": "abs",
  "Bent-Arm Barbell Pullover": "back",
  "Bent-Arm Dumbbell Pullover": "chest",
  "Bent-Knee Hip Raise": "abs",
  "Bicycling": "quads",
  "Bicycling, Stationary": "quads",
  "Board Press": "triceps",
  "Body Tricep Press": "triceps",
  "Body-Up": "triceps",
  "Bodyweight Flyes": "chest",
  "Bodyweight Mid Row": "back",
  "Bodyweight Squat": "quads",
  "Bodyweight Walking Lunge": "quads",
  "Bosu Ball Cable Crunch With Side Bends": "abs",
  "Bottoms Up": "abs",
  "Bottoms-Up Clean From The Hang Position": "forearms",
  "Box Jump (Multiple Response)": "hamstrings",
  "Box Skip": "hamstrings",
  "Box Squat": "quads",
  "Box Squat with Bands": "quads",
  "Box Squat with Chains": "quads",
  "Brachialis-SMR": "biceps",
  "Bradford/Rocky Presses": "shoulders",
  "Butt Lift (Bridge)": "glutes",
  "Butt-Ups": "abs",
  "Butterfly": "chest",
  "Cable Chest Press": "chest",
  "Cable Crossover": "chest",
  "Cable Deadlifts": "quads",
  "Cable Hammer Curls - Rope Attachment": "biceps",
  "Cable Incline Pushdown": "back",
  "Cable Incline Triceps Extension": "triceps",
  "Cable Internal Rotation": "shoulders",
  "Cable Iron Cross": "chest",
  "Cable Judo Flip": "abs",
  "Cable Lying Triceps Extension": "triceps",
  "Cable One Arm Tricep Extension": "triceps",
  "Cable Preacher Curl": "biceps",
  "Cable Reverse Crunch": "abs",
  "Cable Rope Overhead Triceps Extension": "triceps",
  "Cable Rope Rear-Delt Rows": "shoulders",
  "Cable Russian Twists": "abs",
  "Cable Seated Crunch": "abs",
  "Cable Seated Lateral Raise": "shoulders",
  "Cable Shoulder Press": "shoulders",
  "Cable Shrugs": "traps",
  "Cable Wrist Curl": "forearms",
  "Calf Press": "calves",
  "Calf Press On The Leg Press Machine": "calves",
  "Calf Raise On A Dumbbell": "calves",
  "Calf Raises - With Bands": "calves",
  "Calf Stretch Elbows Against Wall": "calves",
  "Calf Stretch Hands Against Wall": "calves",
  "Calf-Machine Shoulder Shrug": "traps",
  "Calves-SMR": "calves",
  "Car Deadlift": "quads",
  "Car Drivers": "shoulders",
  "Carioca Quick Step": "adductors",
  "Cat Stretch": "back",
  "Catch and Overhead Throw": "back",
  "Chain Handle Extension": "triceps",
  "Chain Press": "chest",
  "Chair Leg Extended Stretch": "hamstrings",
  "Chair Lower Back Stretch": "back",
  "Chair Squat": "quads",
  "Chair Upper Body Stretch": "shoulders",
  "Chest And Front Of Shoulder Stretch": "chest",
  "Chest Push (multiple response)": "chest",
  "Chest Push (single response)": "chest",
  "Chest Push from 3 point stance": "chest",
  "Chest Push with Run Release": "chest",
  "Chest Stretch on Stability Ball": "chest",
  "Child's Pose": "back",
  "Chin-Up": "back",
  "Circus Bell": "shoulders",
  "Clean": "hamstrings",
  "Clean and Jerk": "shoulders",
  "Clean and Press": "shoulders",
  "Clean Deadlift": "hamstrings",
  "Clean from Blocks": "quads",
  "Clean Shrug": "traps",
  "Clock Push-Up": "chest",
  "Close-Grip Barbell Bench Press": "triceps",
  "Close-Grip Dumbbell Press": "triceps",
  "Close-Grip EZ Bar Curl": "biceps",
  "Close-Grip EZ-Bar Curl with Band": "biceps",
  "Close-Grip EZ-Bar Press": "triceps",
  "Close-Grip Front Lat Pulldown": "back",
  "Close-Grip Push-Up off of a Dumbbell": "triceps",
  "Close-Grip Standing Barbell Curl": "biceps",
  "Cocoons": "abs",
  "Conan's Wheel": "quads",
  "Concentration Curls": "biceps",
  "Cross Body Hammer Curl": "biceps",
  "Cross Over - With Bands": "chest",
  "Cross-Body Crunch": "abs",
  "Crossover Reverse Lunge": "back",
  "Crucifix": "shoulders",
  "Crunch - Hands Overhead": "abs",
  "Crunch - Legs On Exercise Ball": "abs",
  "Crunches": "abs",
  "Cuban Press": "shoulders",
  "Dancer's Stretch": "back",
  "Dead Bug": "abs",
  "Deadlift with Bands": "back",
  "Deadlift with Chains": "back",
  "Decline Barbell Bench Press": "chest",
  "Decline Close-Grip Bench To Skull Crusher": "triceps",
  "Decline Dumbbell Bench Press": "chest",
  "Decline Dumbbell Flyes": "chest",
  "Decline Dumbbell Triceps Extension": "triceps",
  "Decline EZ Bar Triceps Extension": "triceps",
  "Decline Oblique Crunch": "abs",
  "Decline Push-Up": "chest",
  "Decline Reverse Crunch": "abs",
  "Decline Smith Press": "chest",
  "Deficit Deadlift": "back",
  "Depth Jump Leap": "quads",
  "Dip Machine": "triceps",
  "Dips - Chest Version": "chest",
  "Dips - Triceps Version": "triceps",
  "Donkey Calf Raises": "calves",
  "Double Kettlebell Alternating Hang Clean": "hamstrings",
  "Double Kettlebell Jerk": "shoulders",
  "Double Kettlebell Push Press": "shoulders",
  "Double Kettlebell Snatch": "shoulders",
  "Double Kettlebell Windmill": "abs",
  "Double Leg Butt Kick": "quads",
  "Downward Facing Balance": "glutes",
  "Drag Curl": "biceps",
  "Drop Push": "chest",
  "Dumbbell Alternate Bicep Curl": "biceps",
  "Dumbbell Bench Press with Neutral Grip": "chest",
  "Dumbbell Bicep Curl": "biceps",
  "Dumbbell Clean": "hamstrings",
  "Dumbbell Floor Press": "triceps",
  "Dumbbell Flyes": "chest",
  "Dumbbell Incline Row": "back",
  "Dumbbell Incline Shoulder Raise": "shoulders",
  "Dumbbell Lunges": "quads",
  "Dumbbell Lying One-Arm Rear Lateral Raise": "shoulders",
  "Dumbbell Lying Pronation": "forearms",
  "Dumbbell Lying Rear Lateral Raise": "shoulders",
  "Dumbbell Lying Supination": "forearms",
  "Dumbbell One-Arm Shoulder Press": "shoulders",
  "Dumbbell One-Arm Triceps Extension": "triceps",
  "Dumbbell One-Arm Upright Row": "shoulders",
  "Dumbbell Prone Incline Curl": "biceps",
  "Dumbbell Raise": "shoulders",
  "Dumbbell Rear Lunge": "quads",
  "Dumbbell Scaption": "shoulders",
  "Dumbbell Seated Box Jump": "quads",
  "Dumbbell Seated One-Leg Calf Raise": "calves",
  "Dumbbell Side Bend": "abs",
  "Dumbbell Squat": "quads",
  "Dumbbell Squat To A Bench": "quads",
  "Dumbbell Step Ups": "quads",
  "Dumbbell Tricep Extension -Pronated Grip": "triceps",
  "Dynamic Back Stretch": "back",
  "Dynamic Chest Stretch": "chest",
  "Elbow Circles": "shoulders",
  "Elbow to Knee": "abs",
  "Elbows Back": "chest",
  "Elevated Back Lunge": "quads",
  "Elevated Cable Rows": "back",
  "Elliptical Trainer": "quads",
  "Exercise Ball Crunch": "abs",
  "Exercise Ball Pull-In": "abs",
  "Extended Range One-Arm Kettlebell Floor Press": "chest",
  "External Rotation": "shoulders",
  "External Rotation with Band": "shoulders",
  "External Rotation with Cable": "shoulders",
  "EZ-Bar Skullcrusher": "triceps",
  "Fast Skipping": "quads",
  "Finger Curls": "forearms",
  "Flat Bench Cable Flyes": "chest",
  "Flat Bench Leg Pull-In": "abs",
  "Flat Bench Lying Leg Raise": "abs",
  "Flexor Incline Dumbbell Curls": "biceps",
  "Floor Glute-Ham Raise": "hamstrings",
  "Floor Press": "triceps",
  "Floor Press with Chains": "triceps",
  "Flutter Kicks": "glutes",
  "Foot-SMR": "calves",
  "Forward Drag with Press": "chest",
  "Frankenstein Squat": "quads",
  "Freehand Jump Squat": "quads",
  "Frog Hops": "quads",
  "Frog Sit-Ups": "abs",
  "Front Barbell Squat": "quads",
  "Front Barbell Squat To A Bench": "quads",
  "Front Box Jump": "hamstrings",
  "Front Cable Raise": "shoulders",
  "Front Cone Hops (or hurdle hops)": "quads",
  "Front Dumbbell Raise": "shoulders",
  "Front Incline Dumbbell Raise": "shoulders",
  "Front Leg Raises": "hamstrings",
  "Front Plate Raise": "shoulders",
  "Front Raise And Pullover": "chest",
  "Front Squat (Clean Grip)": "quads",
  "Front Squats With Two Kettlebells": "quads",
  "Front Two-Dumbbell Raise": "shoulders",
  "Full Range-Of-Motion Lat Pulldown": "back",
  "Gironda Sternum Chins": "back",
  "Glute Ham Raise": "hamstrings",
  "Glute Kickback": "glutes",
  "Good Morning off Pins": "hamstrings",
  "Gorilla Chin/Crunch": "abs",
  "Groin and Back Stretch": "adductors",
  "Groiners": "adductors",
  "Hammer Curls": "biceps",
  "Hammer Grip Incline DB Bench Press": "chest",
  "Hamstring Stretch": "hamstrings",
  "Hamstring-SMR": "hamstrings",
  "Handstand Push-Ups": "shoulders",
  "Hang Clean": "quads",
  "Hang Clean - Below the Knees": "quads",
  "Hang Snatch": "hamstrings",
  "Hang Snatch - Below Knees": "hamstrings",
  "Hanging Bar Good Morning": "hamstrings",
  "Hanging Pike": "abs",
  "Heaving Snatch Balance": "quads",
  "Heavy Bag Thrust": "chest",
  "High Cable Curls": "biceps",
  "Hip Circles (prone)": "abductors",
  "Hip Extension with Bands": "glutes",
  "Hip Flexion with Band": "quads",
  "Hip Lift with Band": "glutes",
  "Hug A Ball": "back",
  "Hug Knees To Chest": "back",
  "Hurdle Hops": "hamstrings",
  "Hyperextensions (Back Extensions)": "back",
  "Hyperextensions With No Hyperextension Bench": "back",
  "Iliotibial Tract-SMR": "abductors",
  "Inchworm": "hamstrings",
  "Incline Barbell Triceps Extension": "triceps",
  "Incline Bench Pull": "back",
  "Incline Cable Chest Press": "chest",
  "Incline Cable Flye": "chest",
  "Incline Dumbbell Bench With Palms Facing In": "chest",
  "Incline Dumbbell Flyes": "chest",
  "Incline Dumbbell Flyes - With A Twist": "chest",
  "Incline Hammer Curls": "biceps",
  "Incline Inner Biceps Curl": "biceps",
  "Incline Push-Up": "chest",
  "Incline Push-Up Close-Grip": "triceps",
  "Incline Push-Up Depth Jump": "chest",
  "Incline Push-Up Medium": "chest",
  "Incline Push-Up Reverse Grip": "chest",
  "Incline Push-Up Wide": "chest",
  "Intermediate Groin Stretch": "hamstrings",
  "Intermediate Hip Flexor and Quad Stretch": "quads",
  "Internal Rotation with Band": "shoulders",
  "Inverted Row with Straps": "back",
  "Iron Cross": "shoulders",
  "Iron Crosses (stretch)": "quads",
  "Isometric Chest Squeezes": "chest",
  "Isometric Wipers": "chest",
  "IT Band and Glute Stretch": "abductors",
  "Jackknife Sit-Up": "abs",
  "Janda Sit-Up": "abs",
  "Jefferson Squats": "quads",
  "Jerk Balance": "shoulders",
  "Jerk Dip Squat": "quads",
  "JM Press": "triceps",
  "Jogging, Treadmill": "quads",
  "Keg Load": "back",
  "Kettlebell Arnold Press": "shoulders",
  "Kettlebell Dead Clean": "hamstrings",
  "Kettlebell Figure 8": "abs",
  "Kettlebell Halo": "shoulders",
  "Kettlebell Halo with Overhead Extension": "shoulders",
  "Kettlebell Hang Clean": "hamstrings",
  "Kettlebell One-Legged Deadlift": "hamstrings",
  "Kettlebell Overhead Triceps Extension": "triceps",
  "Kettlebell Pass Between The Legs": "abs",
  "Kettlebell Pirate Ships": "shoulders",
  "Kettlebell Pistol Squat": "quads",
  "Kettlebell Seated Press": "shoulders",
  "Kettlebell Seesaw Press": "shoulders",
  "Kettlebell Sumo High Pull": "traps",
  "Kettlebell Thruster": "shoulders",
  "Kettlebell Turkish Get-Up (Lunge style)": "shoulders",
  "Kettlebell Turkish Get-Up (Squat style)": "shoulders",
  "Kettlebell Windmill": "abs",
  "Kipping Muscle Up": "back",
  "Knee Across The Body": "glutes",
  "Knee Circles": "calves",
  "Knee Tuck Jump": "hamstrings",
  "Knee/Hip Raise On Parallel Bars": "abs",
  "Kneeling Arm Drill": "shoulders",
  "Kneeling Cable Crunch With Alternating Oblique Twists": "abs",
  "Kneeling Cable Triceps Extension": "triceps",
  "Kneeling Forearm Stretch": "forearms",
  "Kneeling High Pulley Row": "back",
  "Kneeling Hip Flexor": "quads",
  "Kneeling Jump Squat": "glutes",
  "Kneeling Single-Arm High Pulley Row": "back",
  "Kneeling Squat": "glutes",
  "Landmine 180's": "abs",
  "Landmine Linear Jammer": "shoulders",
  "Lateral Bound": "adductors",
  "Lateral Box Jump": "adductors",
  "Lateral Cone Hops": "adductors",
  "Lateral Raise - With Bands": "shoulders",
  "Latissimus Dorsi-SMR": "back",
  "Leg Extensions": "quads",
  "Leg Lift": "glutes",
  "Leg Pull-In": "abs",
  "Leg-Over Floor Press": "chest",
  "Leg-Up Hamstring Stretch": "hamstrings",
  "Leverage Chest Press": "chest",
  "Leverage Deadlift": "quads",
  "Leverage Decline Chest Press": "chest",
  "Leverage High Row": "back",
  "Leverage Incline Chest Press": "chest",
  "Leverage Iso Row": "back",
  "Leverage Shoulder Press": "shoulders",
  "Leverage Shrug": "traps",
  "Linear 3-Part Start Technique": "hamstrings",
  "Linear Acceleration Wall Drill": "hamstrings",
  "Linear Depth Jump": "quads",
  "Log Lift": "shoulders",
  "London Bridges": "back",
  "Looking At Ceiling": "quads",
  "Low Cable Crossover": "chest",
  "Low Cable Triceps Extension": "triceps",
  "Low Pulley Row To Neck": "shoulders",
  "Lower Back Curl": "abs",
  "Lower Back-SMR": "back",
  "Lunge Pass Through": "hamstrings",
  "Lunge Sprint": "quads",
  "Lying Bent Leg Groin": "adductors",
  "Lying Cable Curl": "biceps",
  "Lying Cambered Barbell Row": "back",
  "Lying Close-Grip Bar Curl On High Pulley": "biceps",
  "Lying Close-Grip Barbell Triceps Extension Behind The Head": "triceps",
  "Lying Close-Grip Barbell Triceps Press To Chin": "triceps",
  "Lying Crossover": "abductors",
  "Lying Dumbbell Tricep Extension": "triceps",
  "Lying Glute": "glutes",
  "Lying Hamstring": "hamstrings",
  "Lying High Bench Barbell Curl": "biceps",
  "Lying Leg Curls": "hamstrings",
  "Lying Machine Squat": "quads",
  "Lying One-Arm Lateral Raise": "shoulders",
  "Lying Prone Quadriceps": "quads",
  "Lying Rear Delt Raise": "shoulders",
  "Lying Supine Dumbbell Curl": "biceps",
  "Lying T-Bar Row": "back",
  "Lying Triceps Press": "triceps",
  "Machine Bench Press": "chest",
  "Machine Bicep Curl": "biceps",
  "Machine Preacher Curls": "biceps",
  "Machine Shoulder (Military) Press": "shoulders",
  "Medicine Ball Chest Pass": "chest",
  "Medicine Ball Full Twist": "abs",
  "Medicine Ball Scoop Throw": "shoulders",
  "Middle Back Shrug": "back",
  "Middle Back Stretch": "back",
  "Mixed Grip Chin": "back",
  "Monster Walk": "abductors",
  "Mountain Climbers": "quads",
  "Moving Claw Series": "hamstrings",
  "Muscle Snatch": "hamstrings",
  "Muscle Up": "back",
  "Narrow Stance Hack Squats": "quads",
  "Narrow Stance Leg Press": "quads",
  "Narrow Stance Squats": "quads",
  "Natural Glute Ham Raise": "hamstrings",
  "Neck Press": "chest",
  "Oblique Crunches": "abs",
  "Oblique Crunches - On The Floor": "abs",
  "Olympic Squat": "quads",
  "On Your Side Quad Stretch": "quads",
  "On-Your-Back Quad Stretch": "quads",
  "One Arm Against Wall": "back",
  "One Arm Chin-Up": "back",
  "One Arm Dumbbell Bench Press": "chest",
  "One Arm Dumbbell Preacher Curl": "biceps",
  "One Arm Floor Press": "triceps",
  "One Arm Lat Pulldown": "back",
  "One Arm Pronated Dumbbell Triceps Extension": "triceps",
  "One Arm Supinated Dumbbell Triceps Extension": "triceps",
  "One Half Locust": "quads",
  "One Handed Hang": "back",
  "One Knee To Chest": "glutes",
  "One Leg Barbell Squat": "quads",
  "One-Arm Dumbbell Row": "back",
  "One-Arm Flat Bench Dumbbell Flye": "chest",
  "One-Arm High-Pulley Cable Side Bends": "abs",
  "One-Arm Incline Lateral Raise": "shoulders",
  "One-Arm Kettlebell Clean": "hamstrings",
  "One-Arm Kettlebell Clean and Jerk": "shoulders",
  "One-Arm Kettlebell Floor Press": "chest",
  "One-Arm Kettlebell Jerk": "shoulders",
  "One-Arm Kettlebell Military Press To The Side": "shoulders",
  "One-Arm Kettlebell Para Press": "shoulders",
  "One-Arm Kettlebell Push Press": "shoulders",
  "One-Arm Kettlebell Row": "back",
  "One-Arm Kettlebell Snatch": "shoulders",
  "One-Arm Kettlebell Split Jerk": "shoulders",
  "One-Arm Kettlebell Split Snatch": "shoulders",
  "One-Arm Kettlebell Swings": "hamstrings",
  "One-Arm Long Bar Row": "back",
  "One-Arm Medicine Ball Slam": "abs",
  "One-Arm Open Palm Kettlebell Clean": "hamstrings",
  "One-Arm Overhead Kettlebell Squats": "quads",
  "One-Arm Side Deadlift": "quads",
  "One-Arm Side Laterals": "shoulders",
  "One-Legged Cable Kickback": "glutes",
  "Open Palm Kettlebell Clean": "hamstrings",
  "Otis-Up": "abs",
  "Overhead Cable Curl": "biceps",
  "Overhead Lat": "back",
  "Overhead Slam": "back",
  "Overhead Squat": "quads",
  "Overhead Stretch": "abs",
  "Overhead Triceps": "triceps",
  "Pallof Press With Rotation": "abs",
  "Palms-Down Dumbbell Wrist Curl Over A Bench": "forearms",
  "Palms-Down Wrist Curl Over A Bench": "forearms",
  "Palms-Up Barbell Wrist Curl Over A Bench": "forearms",
  "Palms-Up Dumbbell Wrist Curl Over A Bench": "forearms",
  "Parallel Bar Dip": "triceps",
  "Pelvic Tilt Into Bridge": "back",
  "Peroneals Stretch": "calves",
  "Peroneals-SMR": "calves",
  "Physioball Hip Bridge": "glutes",
  "Pin Presses": "triceps",
  "Piriformis-SMR": "glutes",
  "Plank": "abs",
  "Plate Twist": "abs",
  "Platform Hamstring Slides": "hamstrings",
  "Plie Dumbbell Squat": "quads",
  "Plyo Kettlebell Pushups": "chest",
  "Plyo Push-up": "chest",
  "Posterior Tibialis Stretch": "calves",
  "Power Clean": "hamstrings",
  "Power Clean from Blocks": "hamstrings",
  "Power Jerk": "quads",
  "Power Partials": "shoulders",
  "Power Snatch": "hamstrings",
  "Power Snatch from Blocks": "quads",
  "Power Stairs": "hamstrings",
  "Preacher Hammer Dumbbell Curl": "biceps",
  "Press Sit-Up": "abs",
  "Prone Manual Hamstring": "hamstrings",
  "Prowler Sprint": "hamstrings",
  "Pull Through": "glutes",
  "Pullups": "back",
  "Push Press": "shoulders",
  "Push Press - Behind the Neck": "shoulders",
  "Push Up to Side Plank": "chest",
  "Push-Up Wide": "chest",
  "Push-Ups - Close Triceps Position": "triceps",
  "Push-Ups With Feet Elevated": "chest",
  "Push-Ups With Feet On An Exercise Ball": "chest",
  "Pushups": "chest",
  "Pushups (Close and Wide Hand Positions)": "chest",
  "Pyramid": "back",
  "Quad Stretch": "quads",
  "Quadriceps-SMR": "quads",
  "Quick Leap": "quads",
  "Rack Delivery": "shoulders",
  "Rack Pull with Bands": "back",
  "Rack Pulls": "back",
  "Rear Leg Raises": "quads",
  "Recumbent Bike": "quads",
  "Return Push from Stance": "shoulders",
  "Reverse Band Bench Press": "triceps",
  "Reverse Band Box Squat": "quads",
  "Reverse Band Deadlift": "back",
  "Reverse Band Power Squat": "quads",
  "Reverse Band Sumo Deadlift": "hamstrings",
  "Reverse Barbell Curl": "biceps",
  "Reverse Barbell Preacher Curls": "biceps",
  "Reverse Cable Curl": "biceps",
  "Reverse Flyes": "shoulders",
  "Reverse Flyes With External Rotation": "shoulders",
  "Reverse Grip Bent-Over Rows": "back",
  "Reverse Grip Triceps Pushdown": "triceps",
  "Reverse Machine Flyes": "shoulders",
  "Reverse Plate Curls": "biceps",
  "Reverse Triceps Bench Press": "triceps",
  "Rhomboids-SMR": "back",
  "Rickshaw Carry": "forearms",
  "Rickshaw Deadlift": "quads",
  "Ring Dips": "triceps",
  "Rocket Jump": "quads",
  "Rocking Standing Calf Raise": "calves",
  "Rocky Pull-Ups/Pulldowns": "back",
  "Romanian Deadlift from Deficit": "hamstrings",
  "Rope Climb": "back",
  "Rope Crunch": "abs",
  "Rope Jumping": "quads",
  "Rope Straight-Arm Pulldown": "back",
  "Round The World Shoulder Stretch": "shoulders",
  "Rowing, Stationary": "quads",
  "Runner's Stretch": "hamstrings",
  "Running, Treadmill": "quads",
  "Russian Twist": "abs",
  "Sandbag Load": "quads",
  "Scapular Pull-Up": "traps",
  "Scissor Kick": "abs",
  "Scissors Jump": "quads",
  "Seated Band Hamstring Curl": "hamstrings",
  "Seated Barbell Military Press": "shoulders",
  "Seated Barbell Twist": "abs",
  "Seated Bent-Over One-Arm Dumbbell Triceps Extension": "triceps",
  "Seated Bent-Over Rear Delt Raise": "shoulders",
  "Seated Bent-Over Two-Arm Dumbbell Triceps Extension": "triceps",
  "Seated Biceps": "biceps",
  "Seated Cable Rows": "back",
  "Seated Cable Shoulder Press": "shoulders",
  "Seated Calf Stretch": "calves",
  "Seated Close-Grip Concentration Barbell Curl": "biceps",
  "Seated Dumbbell Inner Biceps Curl": "biceps",
  "Seated Dumbbell Palms-Down Wrist Curl": "forearms",
  "Seated Dumbbell Palms-Up Wrist Curl": "forearms",
  "Seated Flat Bench Leg Pull-In": "abs",
  "Seated Floor Hamstring Stretch": "hamstrings",
  "Seated Front Deltoid": "shoulders",
  "Seated Glute": "glutes",
  "Seated Good Mornings": "back",
  "Seated Hamstring": "hamstrings",
  "Seated Hamstring and Calf Stretch": "hamstrings",
  "Seated Leg Tucks": "abs",
  "Seated One-arm Cable Pulley Rows": "back",
  "Seated One-Arm Dumbbell Palms-Down Wrist Curl": "forearms",
  "Seated One-Arm Dumbbell Palms-Up Wrist Curl": "forearms",
  "Seated Overhead Stretch": "abs",
  "Seated Palm-Up Barbell Wrist Curl": "forearms",
  "Seated Palms-Down Barbell Wrist Curl": "forearms",
  "Seated Side Lateral Raise": "shoulders",
  "Seated Triceps Press": "triceps",
  "Seated Two-Arm Palms-Up Low-Pulley Wrist Curl": "forearms",
  "See-Saw Press (Alternating Side Press)": "shoulders",
  "Shotgun Row": "back",
  "Shoulder Circles": "shoulders",
  "Shoulder Press - With Bands": "shoulders",
  "Shoulder Raise": "shoulders",
  "Shoulder Stretch": "shoulders",
  "Side Bridge": "abs",
  "Side Hop-Sprint": "quads",
  "Side Jackknife": "abs",
  "Side Lateral Raise": "shoulders",
  "Side Laterals to Front Raise": "shoulders",
  "Side Leg Raises": "adductors",
  "Side Lying Groin Stretch": "adductors",
  "Side Standing Long Jump": "quads",
  "Side to Side Box Shuffle": "quads",
  "Side To Side Chins": "back",
  "Side Wrist Pull": "shoulders",
  "Side-Lying Floor Stretch": "back",
  "Single Dumbbell Raise": "shoulders",
  "Single Leg Butt Kick": "quads",
  "Single Leg Glute Bridge": "glutes",
  "Single Leg Push-off": "quads",
  "Single-Arm Cable Crossover": "chest",
  "Single-Arm Linear Jammer": "shoulders",
  "Single-Arm Push-Up": "chest",
  "Single-Cone Sprint Drill": "quads",
  "Single-Leg High Box Squat": "quads",
  "Single-Leg Hop Progression": "quads",
  "Single-Leg Lateral Hop": "quads",
  "Single-Leg Leg Extension": "quads",
  "Single-Leg Stride Jump": "quads",
  "Sit Squats": "quads",
  "Sit-Up": "abs",
  "Skating": "quads",
  "Sled Drag - Harness": "quads",
  "Sled Overhead Backward Walk": "shoulders",
  "Sled Overhead Triceps Extension": "triceps",
  "Sled Reverse Flye": "shoulders",
  "Sled Row": "back",
  "Sledgehammer Swings": "abs",
  "Smith Incline Shoulder Raise": "shoulders",
  "Smith Machine Behind the Back Shrug": "traps",
  "Smith Machine Bent Over Row": "back",
  "Smith Machine Close-Grip Bench Press": "triceps",
  "Smith Machine Decline Press": "chest",
  "Smith Machine Hang Power Clean": "hamstrings",
  "Smith Machine Hip Raise": "abs",
  "Smith Machine Incline Bench Press": "chest",
  "Smith Machine Leg Press": "quads",
  "Smith Machine One-Arm Upright Row": "shoulders",
  "Smith Machine Overhead Shoulder Press": "shoulders",
  "Smith Machine Pistol Squat": "quads",
  "Smith Machine Reverse Calf Raises": "calves",
  "Smith Machine Stiff-Legged Deadlift": "hamstrings",
  "Smith Machine Upright Row": "traps",
  "Smith Single-Leg Split Squat": "quads",
  "Snatch": "quads",
  "Snatch Balance": "quads",
  "Snatch Deadlift": "hamstrings",
  "Snatch from Blocks": "quads",
  "Snatch Shrug": "traps",
  "Speed Band Overhead Triceps": "triceps",
  "Speed Box Squat": "quads",
  "Speed Squats": "quads",
  "Spell Caster": "abs",
  "Spider Crawl": "abs",
  "Spinal Stretch": "back",
  "Split Clean": "quads",
  "Split Jerk": "quads",
  "Split Jump": "quads",
  "Split Snatch": "hamstrings",
  "Split Squat with Dumbbells": "quads",
  "Split Squats": "hamstrings",
  "Squat Jerk": "quads",
  "Squat with Bands": "quads",
  "Squat with Chains": "quads",
  "Squat with Plate Movers": "quads",
  "Squats - With Bands": "quads",
  "Stairmaster": "quads",
  "Standing Alternating Dumbbell Press": "shoulders",
  "Standing Barbell Calf Raise": "calves",
  "Standing Barbell Press Behind Neck": "shoulders",
  "Standing Bent-Over One-Arm Dumbbell Triceps Extension": "triceps",
  "Standing Bent-Over Two-Arm Dumbbell Triceps Extension": "triceps",
  "Standing Biceps Cable Curl": "biceps",
  "Standing Biceps Stretch": "biceps",
  "Standing Bradford Press": "shoulders",
  "Standing Cable Chest Press": "chest",
  "Standing Cable Lift": "abs",
  "Standing Cable Wood Chop": "abs",
  "Standing Calf Raises": "calves",
  "Standing Concentration Curl": "biceps",
  "Standing Dumbbell Calf Raise": "calves",
  "Standing Dumbbell Press": "shoulders",
  "Standing Dumbbell Reverse Curl": "biceps",
  "Standing Dumbbell Straight-Arm Front Delt Raise Above Head": "shoulders",
  "Standing Dumbbell Triceps Extension": "triceps",
  "Standing Dumbbell Upright Row": "traps",
  "Standing Elevated Quad Stretch": "quads",
  "Standing Front Barbell Raise Over Head": "shoulders",
  "Standing Gastrocnemius Calf Stretch": "calves",
  "Standing Hamstring and Calf Stretch": "hamstrings",
  "Standing Hip Circles": "abductors",
  "Standing Hip Flexors": "quads",
  "Standing Inner-Biceps Curl": "biceps",
  "Standing Lateral Stretch": "abs",
  "Standing Long Jump": "quads",
  "Standing Low-Pulley Deltoid Raise": "shoulders",
  "Standing Low-Pulley One-Arm Triceps Extension": "triceps",
  "Standing Military Press": "shoulders",
  "Standing Olympic Plate Hand Squeeze": "forearms",
  "Standing One-Arm Cable Curl": "biceps",
  "Standing One-Arm Dumbbell Curl Over Incline Bench": "biceps",
  "Standing One-Arm Dumbbell Triceps Extension": "triceps",
  "Standing Overhead Barbell Triceps Extension": "triceps",
  "Standing Palm-In One-Arm Dumbbell Press": "shoulders",
  "Standing Palms-In Dumbbell Press": "shoulders",
  "Standing Palms-Up Barbell Behind The Back Wrist Curl": "forearms",
  "Standing Pelvic Tilt": "back",
  "Standing Rope Crunch": "abs",
  "Standing Soleus And Achilles Stretch": "calves",
  "Standing Toe Touches": "hamstrings",
  "Standing Towel Triceps Extension": "triceps",
  "Standing Two-Arm Overhead Throw": "shoulders",
  "Star Jump": "quads",
  "Step Mill": "quads",
  "Step-up with Knee Raise": "glutes",
  "Stiff Leg Barbell Good Morning": "back",
  "Stiff-Legged Barbell Deadlift": "hamstrings",
  "Stiff-Legged Dumbbell Deadlift": "hamstrings",
  "Stomach Vacuum": "abs",
  "Straight Bar Bench Mid Rows": "back",
  "Straight Raises on Incline Bench": "shoulders",
  "Straight-Arm Dumbbell Pullover": "chest",
  "Stride Jump Crossover": "quads",
  "Sumo Deadlift with Bands": "hamstrings",
  "Sumo Deadlift with Chains": "hamstrings",
  "Superman": "back",
  "Supine Chest Throw": "triceps",
  "Supine One-Arm Overhead Throw": "abs",
  "Supine Two-Arm Overhead Throw": "abs",
  "Suspended Fallout": "abs",
  "Suspended Push-Up": "chest",
  "Suspended Reverse Crunch": "abs",
  "Suspended Row": "back",
  "Suspended Split Squat": "quads",
  "T-Bar Row with Handle": "back",
  "Tate Press": "triceps",
  "The Straddle": "hamstrings",
  "Thigh Abductor": "abductors",
  "Thigh Adductor": "adductors",
  "Tire Flip": "quads",
  "Toe Touchers": "abs",
  "Torso Rotation": "abs",
  "Trail Running/Walking": "quads",
  "Tricep Dumbbell Kickback": "triceps",
  "Tricep Side Stretch": "triceps",
  "Triceps Overhead Extension with Rope": "triceps",
  "Triceps Pushdown - Rope Attachment": "triceps",
  "Triceps Pushdown - V-Bar Attachment": "triceps",
  "Triceps Stretch": "triceps",
  "Tuck Crunch": "abs",
  "Two-Arm Dumbbell Preacher Curl": "biceps",
  "Two-Arm Kettlebell Clean": "shoulders",
  "Two-Arm Kettlebell Jerk": "shoulders",
  "Two-Arm Kettlebell Military Press": "shoulders",
  "Two-Arm Kettlebell Row": "back",
  "Underhand Cable Pulldowns": "back",
  "Upper Back Stretch": "back",
  "Upper Back-Leg Grab": "hamstrings",
  "Upright Barbell Row": "shoulders",
  "Upright Cable Row": "traps",
  "Upright Row - With Bands": "traps",
  "Upward Stretch": "shoulders",
  "V-Bar Pulldown": "back",
  "V-Bar Pullup": "back",
  "Vertical Swing": "hamstrings",
  "Walking, Treadmill": "quads",
  "Weighted Ball Hyperextension": "back",
  "Weighted Ball Side Bend": "abs",
  "Weighted Bench Dip": "triceps",
  "Weighted Crunches": "abs",
  "Weighted Jump Squat": "quads",
  "Weighted Pull Ups": "back",
  "Weighted Sissy Squat": "quads",
  "Weighted Sit-Ups - With Bands": "abs",
  "Weighted Squat": "quads",
  "Wide Stance Barbell Squat": "quads",
  "Wide Stance Stiff Legs": "hamstrings",
  "Wide-Grip Barbell Bench Press": "chest",
  "Wide-Grip Decline Barbell Bench Press": "chest",
  "Wide-Grip Decline Barbell Pullover": "chest",
  "Wide-Grip Pulldown Behind The Neck": "back",
  "Wide-Grip Rear Pull-Up": "back",
  "Wide-Grip Standing Barbell Curl": "biceps",
  "Wind Sprints": "abs",
  "Windmills": "abductors",
  "World's Greatest Stretch": "hamstrings",
  "Wrist Circles": "forearms",
  "Wrist Rotations with Straight Bar": "forearms",
  "Yoke Walk": "quads",
  "Zercher Squats": "quads",
  "Zottman Preacher Curl": "biceps",
};
// === AUTO-GENERATED: END ===

// Build a normalized lookup to allow case-insensitive matching. The
// generated table (free-exercise-db, ~800 names) is the broad-coverage
// base; the hand-curated table above always wins on name conflicts.
const normalizedExerciseMuscleMap = Object.fromEntries([
  ...Object.entries(generatedExerciseMuscleMap).map(([name, muscle]) => [name.toLowerCase(), muscle]),
  ...Object.entries(exerciseMuscleMap).map(([name, muscle]) => [name.toLowerCase(), muscle])
]);

// Per-user overrides set from Settings → Advanced ("create new exercise" /
// reassign muscle group). Lives only in memory here — src/js/customExercises.js
// owns persistence and calls setCustomExerciseMuscleMap() to push the user's
// saved overrides in after login. Deliberately checked *before* the tables
// above so an advanced lifter's own assignment always wins, including for
// exercise names this file already has an opinion on.
let customExerciseMuscleMap = {};

function setCustomExerciseMuscleMap(map) {
  customExerciseMuscleMap = (map && typeof map === 'object') ? map : {};
}

// Every exercise name this file can resolve to a muscle group, in its
// original casing — the canonical catalog used to constrain the exercise
// entry autocomplete (src/js/customExercises.js adds the user's own custom
// names on top of this at render time).
function getAllExerciseNames() {
  return [...Object.keys(generatedExerciseMuscleMap), ...Object.keys(exerciseMuscleMap)];
}

// Utility to look up a muscle group by exercise name (case-insensitive)
function getMuscleGroup(exerciseName) {
  if (typeof exerciseName !== 'string') {
    return 'other';
  }
  const normalized = exerciseName.trim().toLowerCase();
  return customExerciseMuscleMap[normalized] || normalizedExerciseMuscleMap[normalized] || 'other';
}

if (typeof module !== 'undefined') {
  module.exports = { exerciseMuscleMap, getMuscleGroup, setCustomExerciseMuscleMap, getAllExerciseNames };
}
if (typeof window !== 'undefined') {
  window.exerciseMuscleMap = exerciseMuscleMap;
  window.getMuscleGroup = getMuscleGroup;
  window.setCustomExerciseMuscleMap = setCustomExerciseMuscleMap;
  window.getAllExerciseNames = getAllExerciseNames;
}
