// Map of exercise names to their primary muscle group
// Resistance-training focused, gym-centric.
// Primary target only; many movements have strong secondary muscles.
const exerciseMuscleMap = {
  // ===== Chest =====
  'Bench Press': 'chest',
  'Barbell Bench Press': 'chest',
  'Dumbbell Bench Press': 'chest',
  'Machine Chest Press': 'chest',
  'Smith Machine Bench Press': 'chest',
  'Incline Bench Press': 'chest',
  'Incline Barbell Press': 'chest',
  'Incline Dumbbell Press': 'chest',
  'Incline Machine Press': 'chest',
  'Decline Bench Press': 'chest',
  'Decline Dumbbell Press': 'chest',
  'Decline Machine Press': 'chest',
  'Push Up': 'chest',
  'Weighted Push Up': 'chest',
  'Cable Fly': 'chest',
  'High-to-Low Cable Fly': 'chest',
  'Low-to-High Cable Fly': 'chest',
  'Pec Deck': 'chest',
  'Chest Fly': 'chest',
  'Dumbbell Fly': 'chest',
  'Chest Dip': 'chest',
  'Svend Press': 'chest',
  'Landmine Press (Chest Focus)': 'chest',

  // ===== Back (lats + general back) =====
  'Deadlift': 'back',
  'Conventional Deadlift': 'back',
  'Trap Bar Deadlift': 'back',
  'Sumo Deadlift': 'back',
  'Barbell Row': 'back',
  'Bent-Over Barbell Row': 'back',
  'Pendlay Row': 'back',
  'T-Bar Row': 'back',
  'Chest Supported Row': 'back',
  'Seal Row': 'back',
  'Dumbbell Row': 'back',
  'Single-Arm Dumbbell Row': 'back',
  'Meadows Row': 'back',
  'Inverted Row': 'back',
  'Cable Row': 'back',
  'Seated Cable Row': 'back',
  'Machine Row': 'back',
  'Hammer Strength Row': 'back',
  'Lat Pulldown': 'back',
  'Wide-Grip Lat Pulldown': 'back',
  'Close-Grip Lat Pulldown': 'back',
  'Neutral-Grip Lat Pulldown': 'back',
  'Straight-Arm Pulldown': 'back',
  'Pull Up': 'back',
  'Chin Up': 'back',
  'Neutral-Grip Pull Up': 'back',
  'Assisted Pull Up': 'back',
  'Pullover (Machine)': 'back',
  'Dumbbell Pullover': 'back',
  'Cable Pullover': 'back',
  'Landmine Row': 'back',
  'Kroc Row': 'back',

  // ===== Shoulders =====
  'Overhead Press': 'shoulders',
  'Barbell Overhead Press': 'shoulders',
  'Standing Overhead Press': 'shoulders',
  'Seated Overhead Press': 'shoulders',
  'Dumbbell Shoulder Press': 'shoulders',
  'Seated Dumbbell Press': 'shoulders',
  'Arnold Press': 'shoulders',
  'Machine Shoulder Press': 'shoulders',
  'Smith Machine Overhead Press': 'shoulders',
  'Lateral Raise': 'shoulders',
  'Cable Lateral Raise': 'shoulders',
  'Machine Lateral Raise': 'shoulders',
  'Dumbbell Lateral Raise': 'shoulders',
  'Front Raise': 'shoulders',
  'Plate Front Raise': 'shoulders',
  'Cable Front Raise': 'shoulders',
  'Rear Delt Fly': 'shoulders',
  'Reverse Pec Deck': 'shoulders',
  'Cable Rear Delt Fly': 'shoulders',
  'Face Pull': 'shoulders',
  'Upright Row': 'shoulders',
  'Landmine Press': 'shoulders',

  // ===== Traps =====
  'Barbell Shrug': 'traps',
  'Dumbbell Shrug': 'traps',
  'Smith Machine Shrug': 'traps',
  'Cable Shrug': 'traps',
  'Behind-the-Back Barbell Shrug': 'traps',
  "Farmer's Walk": 'traps',

  // ===== Biceps =====
  'Curl': 'biceps',
  'Barbell Curl': 'biceps',
  'EZ-Bar Curl': 'biceps',
  'Dumbbell Curl': 'biceps',
  'Alternating Dumbbell Curl': 'biceps',
  'Incline Dumbbell Curl': 'biceps',
  'Seated Dumbbell Curl': 'biceps',
  'Preacher Curl': 'biceps',
  'Machine Preacher Curl': 'biceps',
  'Cable Curl': 'biceps',
  'Rope Cable Curl': 'biceps',
  'Concentration Curl': 'biceps',
  'Spider Curl': 'biceps',
  'Bayesian Cable Curl': 'biceps',
  'Hammer Curl': 'biceps',
  'Cross-Body Hammer Curl': 'biceps',
  'Reverse Curl': 'biceps',
  'Zottman Curl': 'biceps',

  // ===== Triceps =====
  'Dip': 'triceps',
  'Triceps Dip': 'triceps',
  'Close-Grip Bench Press': 'triceps',
  'Skull Crusher': 'triceps',
  'EZ-Bar Skull Crusher': 'triceps',
  'Lying Triceps Extension': 'triceps',
  'Overhead Triceps Extension': 'triceps',
  'Seated Overhead Dumbbell Extension': 'triceps',
  'Cable Overhead Triceps Extension': 'triceps',
  'Triceps Pushdown': 'triceps',
  'Cable Triceps Pushdown': 'triceps',
  'Rope Pushdown': 'triceps',
  'V-Bar Pushdown': 'triceps',
  'Single-Arm Cable Pushdown': 'triceps',
  'Kickback': 'triceps',
  'Dumbbell Triceps Kickback': 'triceps',
  'Machine Triceps Extension': 'triceps',

  // ===== Forearms =====
  'Wrist Curl': 'forearms',
  'Reverse Wrist Curl': 'forearms',
  'Behind-the-Back Wrist Curl': 'forearms',
  'Wrist Roller': 'forearms',
  'Plate Pinch': 'forearms',
  'Reverse Curl (Forearm Focus)': 'forearms',
  "Farmer's Carry": 'forearms',
  'Towel Pull Up': 'forearms',

  // ===== Quads =====
  'Squat': 'quads',
  'Back Squat': 'quads',
  'High-Bar Squat': 'quads',
  'Front Squat': 'quads',
  'Smith Machine Squat': 'quads',
  'Hack Squat': 'quads',
  'Machine Hack Squat': 'quads',
  'Sissy Squat': 'quads',
  'Goblet Squat': 'quads',
  'Leg Extension': 'quads',
  'Single-Leg Extension': 'quads',
  'Leg Press': 'quads',
  'Narrow-Stance Leg Press': 'quads',
  'Walking Lunge': 'quads',
  'Forward Lunge': 'quads',
  'Reverse Lunge': 'quads',
  'Deficit Lunge': 'quads',
  'Split Squat': 'quads',
  'Bulgarian Split Squat': 'quads',
  'Step Up': 'quads',

  // ===== Hamstrings =====
  'Romanian Deadlift': 'hamstrings',
  'Stiff-Leg Deadlift': 'hamstrings',
  'Good Morning': 'hamstrings',
  'Leg Curl': 'hamstrings',
  'Seated Leg Curl': 'hamstrings',
  'Lying Leg Curl': 'hamstrings',
  'Standing Leg Curl': 'hamstrings',
  'Nordic Curl': 'hamstrings',
  'Glute-Ham Raise': 'hamstrings',
  'Cable Pull-Through (Hamstrings)': 'hamstrings',
  'Back Extension (Hamstrings)': 'hamstrings',

  // ===== Glutes =====
  'Hip Thrust': 'glutes',
  'Barbell Hip Thrust': 'glutes',
  'Smith Machine Hip Thrust': 'glutes',
  'Glute Bridge': 'glutes',
  'Single-Leg Hip Thrust': 'glutes',
  'Cable Pull-Through': 'glutes',
  'Kettlebell Swing': 'glutes',
  'Step-Up (Glute Focus)': 'glutes',
  'Reverse Lunge (Glute Focus)': 'glutes',
  'Curtsy Lunge': 'glutes',
  '45-Degree Back Extension (Glutes)': 'glutes',
  'Frog Pump': 'glutes',
  'Hip Abduction (Cable)': 'glutes',

  // ===== Calves =====
  'Calf Raise': 'calves',
  'Standing Calf Raise': 'calves',
  'Seated Calf Raise': 'calves',
  'Donkey Calf Raise': 'calves',
  'Leg Press Calf Raise': 'calves',
  'Single-Leg Calf Raise': 'calves',
  'Smith Machine Calf Raise': 'calves',
  'Tibialis Raise': 'calves', // anterior lower leg; keep under calves for simplicity

  // ===== Adductors / Abductors =====
  'Hip Adductor Machine': 'adductors',
  'Hip Abductor Machine': 'abductors',
  'Cable Hip Adduction': 'adductors',
  'Cable Hip Abduction': 'abductors',
  'Side-Lying Hip Abduction': 'abductors',

  // ===== Core / Abs =====
  'Crunch': 'abs',
  'Cable Crunch': 'abs',
  'Machine Crunch': 'abs',
  'Decline Crunch': 'abs',
  'Hanging Knee Raise': 'abs',
  'Hanging Leg Raise': 'abs',
  "Captain's Chair Leg Raise": 'abs',
  'Reverse Crunch': 'abs',
  'Ab Wheel Rollout': 'abs',
  'Plank (Weighted)': 'abs',
  'Side Plank (Weighted)': 'abs',
  'Russian Twist (Weighted)': 'abs',
  'Pallof Press': 'abs',
  'Toe Touch (Weighted)': 'abs',

  // ===== Lower Back (grouped under back for simplicity) =====
  'Back Extension': 'back',
  '45-Degree Back Extension': 'back',
  'Reverse Hyperextension': 'back',
  'Superman (Weighted)': 'back',

  // ===== Misc / Full-body (choose primary) =====
  'Clean Pull': 'back',
  'Snatch Pull': 'back',
  'Power Clean (Strength Accessory)': 'back',
  'Landmine Deadlift': 'back',
  'Sled Push': 'legs',
  'Sled Drag': 'hamstrings',
  "Farmer's Walk (Heavy)": 'traps',
  'Yoke Carry': 'traps',
};

// Utility to look up a muscle group by exercise name
function getMuscleGroup(exerciseName) {
  return exerciseMuscleMap[exerciseName] || 'other';
}

if (typeof module !== 'undefined') {
  module.exports = { exerciseMuscleMap, getMuscleGroup };
}
if (typeof window !== 'undefined') {
  window.exerciseMuscleMap = exerciseMuscleMap;
  window.getMuscleGroup = getMuscleGroup;
}
