/* Master plan preview: renders a plan ("pocketcoach.plan/1", generated by
   the backend's src/plan/generator.js) as a phase timeline with each phase's
   dates, end criteria, nutrition targets and training volume.

   Shared by the athlete's Program tab ("My Plan", the published plan) and
   the coach dashboard (a draft, before approving and publishing). The coach
   view also shows each number's rule, unverified rules and red flags.

   Pure: render() returns an HTML string; nothing here touches storage. */
(function (globalScope) {
  'use strict';

  const PHASE_LABELS = { cut: 'Cut', maintain: 'Maintain', build: 'Build' };
  const MUSCLE_LABELS = {
    chest: 'Chest', back: 'Back', shoulders: 'Shoulders', biceps: 'Biceps', triceps: 'Triceps',
    quads: 'Quads', hamstrings: 'Hamstrings', glutes: 'Glutes', calves: 'Calves',
  };

  function esc(value) {
    return String(value ?? '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
  }

  function fmtDate(iso) {
    if (!iso) return '';
    const d = new Date(`${iso}T00:00:00Z`);
    return d.toLocaleDateString(undefined, { day: 'numeric', month: 'short', year: 'numeric', timeZone: 'UTC' });
  }

  function todayIso() {
    const d = new Date();
    return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;
  }

  function phaseStart(p) { return p.actualStart || p.plannedStart; }
  function phaseEnd(p) { return p.actualEnd || p.plannedEnd; }

  /** The phase whose dates contain `today`, or null before/after the plan. */
  function currentPhase(plan, today = todayIso()) {
    return (plan?.phases || []).find((p) => phaseStart(p) <= today && today <= phaseEnd(p)) || null;
  }

  /** 1-based week of `today` within `phase`. */
  function weekOfPhase(phase, today = todayIso()) {
    const start = Date.parse(`${phaseStart(phase)}T00:00:00Z`);
    const now = Date.parse(`${today}T00:00:00Z`);
    return Math.max(1, Math.floor((now - start) / (7 * 86400000)) + 1);
  }

  function endCriteriaText(phase) {
    const parts = (phase.endCriteria?.any || []).map((c) => {
      if (c.kind === 'timeCap') return `after ${c.weeks} weeks`;
      if (c.kind === 'target') {
        const metric = c.metric === 'bodyweightKg7dAvg' ? 'bodyweight (7-day average)' : c.metric;
        return c.value == null
          ? `when you reach the ${metric} target your coach sets`
          : `when ${metric} ${c.op === '<=' ? '≤' : c.op === '>=' ? '≥' : c.op} ${c.value}${c.metric === 'bodyweightKg7dAvg' ? ' kg' : ''}`;
      }
      return '';
    }).filter(Boolean);
    if (!parts.length) return '';
    return parts.length > 1 ? `Ends ${parts.join(' or ')}, whichever comes first.` : `Ends ${parts[0]}.`;
  }

  function dayTargets(label, t) {
    if (!t) return '';
    return `<div class="pp-day"><div class="pp-day-label">${esc(label)}</div>
      <div class="pp-kcal">${esc(Math.round(t.kcal))} <span>kcal</span></div>
      <div class="pp-macros"><span>P ${esc(Math.round(t.proteinG))} g</span> · <span>F ${esc(Math.round(t.fatG))} g</span> · <span>C ${esc(Math.round(t.carbG))} g</span></div></div>`;
  }

  function ruleTag(prov) {
    if (!prov || !prov.ruleId) return '';
    return `<span class="pp-rule${prov.verified ? '' : ' pp-rule--unverified'}" title="${prov.verified ? 'Verified rule' : 'Not yet verified against Butters University'}">${esc(prov.ruleId)}${prov.verified ? '' : ' ?'}</span>`;
  }

  const flagKey = (f) => `${f.niveau}|${f.bericht}`;

  // Flags raised by every phase come from the intake itself (injuries,
  // sleep, stress, PEDs...): show those once, and per phase only its own.
  function splitFlags(plan) {
    const lists = plan.phases.map((p) => (p.redFlags || []).map(flagKey));
    const common = new Set((lists[0] || []).filter((k) => lists.every((l) => l.includes(k))));
    const shared = (plan.phases[0]?.redFlags || []).filter((f) => common.has(flagKey(f)));
    return { shared, common };
  }

  function flagList(flags) {
    return flags.length ? `<ul class="pp-flags">${flags.map((f) => `<li class="pp-flag pp-flag--${esc(f.niveau)}">${esc(f.bericht)}</li>`).join('')}</ul>` : '';
  }

  function renderPhase(phase, { today, coachView, commonFlags }) {
    const isCurrent = phaseStart(phase) <= today && today <= phaseEnd(phase);
    const n = phase.nutrition || {};
    const t = phase.training || {};
    const sets = Object.entries(t.weeklySetsPerMuscle || {})
      .map(([m, v]) => `<span class="pp-chip">${esc(MUSCLE_LABELS[m] || m)} ${esc(v)}</span>`).join('');
    const deload = t.deloads?.mode === 'reactive'
      ? `Deload an exercise only when its performance drops unexpectedly${t.deloads.triggerStrengthLossPct ? ` (more than ${esc(t.deloads.triggerStrengthLossPct)}% strength loss)` : ''}.`
      : (t.deloads?.intervalWeeks ? `Deload every ${esc(t.deloads.intervalWeeks)} weeks.` : '');
    const progression = t.progression?.scheme === 'double_progression' && Array.isArray(t.progression.repRange)
      ? `Double progression in ${esc(t.progression.repRange[0])}–${esc(t.progression.repRange[1])} reps: add reps, then the smallest load step.`
      : '';
    const flags = coachView ? flagList((phase.redFlags || []).filter((f) => !commonFlags.has(flagKey(f)))) : '';
    const prov = coachView
      ? `<div class="pp-prov">${ruleTag(n.provenance?.kcal)}${ruleTag(n.provenance?.proteinG)}${ruleTag(n.provenance?.fatG)}${ruleTag(t.provenance?.weeklySetsPerMuscle)}</div>`
      : '';

    return `<section class="pp-phase pp-phase--${esc(phase.type)}${isCurrent ? ' pp-phase--current' : ''}">
      <header class="pp-phase-head">
        <span class="pp-phase-name">${esc(PHASE_LABELS[phase.type] || phase.type)}</span>
        <span class="pp-phase-dates">${esc(fmtDate(phaseStart(phase)))} – ${esc(fmtDate(phaseEnd(phase)))} · ${esc(phase.caps?.maxWeeks)} wk</span>
        ${isCurrent ? `<span class="pp-now">Now · week ${esc(weekOfPhase(phase, today))}</span>` : ''}
      </header>
      <p class="pp-ends">${esc(endCriteriaText(phase))}</p>
      <div class="pp-days">${dayTargets('Rest day', n.restDay)}${dayTargets('Training day', n.trainingDay)}</div>
      <div class="pp-training">
        <div class="pp-sub">${esc(t.split?.naam || '')}${t.split?.sessionsPerWeek ? ` · ${esc(t.split.sessionsPerWeek)}×/week` : ''} · weekly sets per muscle</div>
        <div class="pp-chips">${sets}</div>
        ${progression ? `<p class="pp-note">${progression}</p>` : ''}
        ${deload ? `<p class="pp-note">${deload}</p>` : ''}
      </div>
      ${prov}${flags}
    </section>`;
  }

  function renderTimeline(plan, today) {
    const total = plan.phases.reduce((s, p) => s + (p.caps?.maxWeeks || 0), 0) || 1;
    const segs = plan.phases.map((p) => {
      const current = phaseStart(p) <= today && today <= phaseEnd(p);
      return `<div class="pp-seg pp-seg--${esc(p.type)}${current ? ' pp-seg--current' : ''}" style="flex:${(p.caps?.maxWeeks || 0) / total}" title="${esc(PHASE_LABELS[p.type] || p.type)} · ${esc(p.caps?.maxWeeks)} weeks"><span class="pp-seg-name">${esc(PHASE_LABELS[p.type] || p.type)}&nbsp;</span>${esc(p.caps?.maxWeeks)}w</div>`;
    }).join('');
    return `<div class="pp-timeline">${segs}</div>`;
  }

  function render(plan, options = {}) {
    if (!plan || !Array.isArray(plan.phases) || !plan.phases.length) return '<div class="pp-empty">No plan to show.</div>';
    const today = options.today || todayIso();
    const coachView = !!options.coachView;
    const pkg = plan.package || {};
    const first = plan.phases[0];
    const last = plan.phases[plan.phases.length - 1];
    const status = plan.status && plan.status !== 'published'
      ? `<span class="pp-status pp-status--${esc(plan.status)}">${esc(plan.status === 'draft' ? 'Draft — not visible to the client' : plan.status === 'approved' ? 'Approved — not published yet' : plan.status)}</span>`
      : '';
    const review = coachView && (plan.unverifiedRules || []).length
      ? `<p class="pp-review">${esc(plan.unverifiedRules.length)} of the rules behind these numbers are not yet verified against Butters University (marked “?”).${plan.status === 'draft' ? ' Check them before approving.' : ''}</p>`
      : '';
    const conflicts = coachView ? ((plan.butters && plan.butters.conflicts) || []) : [];
    const buConflicts = conflicts.length
      ? `<div class="pp-review pp-review--conflict"><div class="pp-sub">Differs from Butters University</div><ul class="pp-bu">${conflicts.map((c) => `<li><span class="pp-rule">${esc(c.ruleId)}</span> ${esc(c.note)}</li>`).join('')}</ul></div>`
      : '';
    const { shared, common } = splitFlags(plan);
    const intakeFlags = coachView && shared.length ? `<div class="pp-intake-flags"><div class="pp-sub">From the intake</div>${flagList(shared)}</div>` : '';
    const overrides = coachView && (plan.overrides || []).length
      ? `<p class="pp-note">${esc(plan.overrides.length)} coach adjustment${plan.overrides.length === 1 ? '' : 's'} recorded.</p>`
      : '';
    return `<div class="pp-root">
      <header class="pp-head">
        <div class="pp-title">${esc(pkg.name || 'Your plan')}</div>
        <div class="pp-meta">${esc(pkg.totalWeeks)} weeks · ${esc(fmtDate(phaseStart(first)))} – ${esc(fmtDate(phaseEnd(last)))}${coachView && pkg.tier ? ` · ${esc(pkg.tier)}` : ''}</div>
        ${status}
      </header>
      ${review}${buConflicts}${overrides}${intakeFlags}
      ${renderTimeline(plan, today)}
      ${plan.phases.map((p) => renderPhase(p, { today, coachView, commonFlags: common })).join('')}
      ${coachView && plan.ruleVersion ? `<p class="pp-footer">Rules: ${esc(plan.ruleVersion)}</p>` : ''}
    </div>`;
  }

  const STYLE_ID = 'plan-preview-style';
  // Built on the app's design tokens (Anton / Barlow Condensed / Archivo,
  // dark cards, green primary, gold highlight), with fallbacks for pages
  // that don't load the theme.
  const CSS = `
.pp-root{display:flex;flex-direction:column;gap:var(--space-3,12px);padding:4px 0;font-family:var(--font-body,inherit);color:var(--text-color,inherit)}
.pp-head{display:flex;flex-direction:column;gap:4px}
.pp-title{font-family:var(--font-display,inherit);font-size:28px;line-height:1.05;text-transform:uppercase;color:var(--text-color,inherit)}
.pp-meta,.pp-footer{font-family:var(--font-label,inherit);font-size:13px;font-weight:700;letter-spacing:.11em;text-transform:uppercase;color:var(--text-muted,#8c9891)}
.pp-sub,.pp-day-label{font-family:var(--font-label,inherit);font-size:12px;font-weight:700;letter-spacing:.11em;text-transform:uppercase;color:var(--text-muted,#8c9891)}
.pp-status{align-self:flex-start;margin-top:4px;padding:4px 10px;border-radius:var(--radius-pill,999px);font-family:var(--font-label,inherit);font-size:12px;font-weight:700;letter-spacing:.08em;text-transform:uppercase;background:rgba(199,154,84,.16);color:var(--highlight,#c79a54);border:1px solid rgba(199,154,84,.35)}
.pp-review{margin:0;padding:10px 12px;border-radius:var(--radius-sm,12px);background:rgba(199,154,84,.10);border:1px solid rgba(199,154,84,.30);font-size:14px;color:var(--secondary-text,inherit)}
.pp-timeline{display:flex;gap:4px;min-height:34px}
.pp-seg{display:flex;align-items:center;justify-content:center;border-radius:var(--radius-micro,8px);font-family:var(--font-label,inherit);font-size:12px;font-weight:700;letter-spacing:.08em;text-transform:uppercase;color:#050c08;padding:0 6px;white-space:nowrap;overflow:hidden;opacity:.55}
.pp-seg--current{opacity:1;box-shadow:0 0 0 2px var(--text-color,#f4f7f5) inset}
.pp-seg--build,.pp-phase--build .pp-phase-name{background:linear-gradient(135deg,#2f8a63,#236b4e)}
.pp-seg--maintain,.pp-phase--maintain .pp-phase-name{background:linear-gradient(135deg,#d4ab68,#b3843f)}
.pp-seg--cut,.pp-phase--cut .pp-phase-name{background:linear-gradient(135deg,#c4664a,#9b4632)}
.pp-phase{background:var(--card-bg,rgba(127,127,127,.06));border:1px solid var(--border-color,rgba(127,127,127,.25));border-radius:var(--radius-md,16px);padding:var(--space-4,16px);display:flex;flex-direction:column;gap:var(--space-3,12px)}
.pp-phase--current{border-color:var(--primary,#2f8a63);box-shadow:0 0 0 1px var(--primary,#2f8a63)}
.pp-phase-head{display:flex;flex-wrap:wrap;align-items:center;gap:8px}
.pp-phase-name{color:#050c08;font-family:var(--font-label,inherit);font-weight:700;font-size:13px;letter-spacing:.11em;text-transform:uppercase;padding:4px 10px;border-radius:var(--radius-pill,999px)}
.pp-phase-dates{font-family:var(--font-label,inherit);font-size:13px;font-weight:700;letter-spacing:.06em;text-transform:uppercase;color:var(--secondary-text,#b8c2bc)}
.pp-now{margin-left:auto;font-family:var(--font-label,inherit);font-size:12px;font-weight:700;letter-spacing:.11em;text-transform:uppercase;color:var(--primary-text,#42a679)}
.pp-ends,.pp-note{margin:0;font-size:14px;line-height:1.45;color:var(--secondary-text,inherit)}
.pp-days{display:grid;grid-template-columns:1fr 1fr;gap:var(--space-2,8px)}
.pp-day{background:var(--elevated-bg,rgba(127,127,127,.08));border-radius:var(--radius-sm,12px);padding:10px 12px}
.pp-kcal{font-family:var(--font-display,inherit);font-size:30px;line-height:1.1;color:var(--text-color,inherit)}
.pp-kcal span{font-family:var(--font-label,inherit);font-size:13px;font-weight:700;letter-spacing:.11em;text-transform:uppercase;color:var(--text-muted,#8c9891);margin-left:4px}
.pp-macros span{white-space:nowrap}
.pp-macros{font-family:var(--font-label,inherit);font-size:14px;font-weight:600;letter-spacing:.04em;color:var(--secondary-text,inherit)}
.pp-training{display:flex;flex-direction:column;gap:8px}
.pp-chips,.pp-prov{display:flex;flex-wrap:wrap;gap:6px}
.pp-chip{font-family:var(--font-label,inherit);font-size:13px;font-weight:700;letter-spacing:.04em;padding:4px 10px;border-radius:var(--radius-pill,999px);background:var(--elevated-bg,rgba(127,127,127,.12));border:1px solid var(--border-color,rgba(127,127,127,.25));color:var(--text-color,inherit)}
.pp-rule{font-family:ui-monospace,monospace;font-size:11px;padding:2px 8px;border-radius:var(--radius-micro,8px);background:var(--elevated-bg,rgba(127,127,127,.12));color:var(--secondary-text,inherit)}
.pp-rule--unverified{background:rgba(199,154,84,.16);color:var(--highlight,#c79a54)}
.pp-intake-flags{padding:10px 12px;border-radius:var(--radius-sm,12px);border:1px solid var(--border-color,rgba(127,127,127,.25))}
.pp-flags{margin:6px 0 0;padding-left:18px;font-size:13px}
.pp-review--conflict{background:rgba(176,90,60,.10);border-color:rgba(176,90,60,.35)}
.pp-bu{margin:6px 0 0;padding-left:18px;font-size:13px}
.pp-bu li{margin:4px 0}
.pp-flag--rood{color:#e0796a}.pp-flag--oranje{color:var(--highlight,#c79a54)}.pp-flag--info{color:var(--secondary-text,inherit)}
.pp-empty{padding:24px 16px;text-align:center;color:var(--secondary-text,#888);border:1px dashed var(--border-color,rgba(127,127,127,.3));border-radius:var(--radius-md,16px)}
.pp-empty strong{display:block;font-family:var(--font-display,inherit);font-size:22px;text-transform:uppercase;color:var(--text-color,inherit);margin-bottom:6px}
@media (max-width:420px){.pp-seg-name{display:none}.pp-kcal{font-size:26px}}`;

  function ensureStyles(doc = globalScope.document) {
    if (!doc || doc.getElementById(STYLE_ID)) return;
    const style = doc.createElement('style');
    style.id = STYLE_ID;
    style.textContent = CSS;
    doc.head.appendChild(style);
  }

  const api = { render, currentPhase, weekOfPhase, endCriteriaText, ensureStyles };
  if (typeof module !== 'undefined' && module.exports) module.exports = api;
  globalScope.PlanPreview = api;
})(typeof window !== 'undefined' ? window : globalThis);
